version: '3.8'
services:
  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - telemetry
      - commands
      - authentication
      - dashboard
  telemetry:
    build: ./telemetry_service
    ports:
      - "8001:8001"
    environment:
      - DJANGO_SETTINGS_MODULE=telemetry_service.settings
    depends_on:
      - telemetry_db
      - redis
  telemetry_db:
    image: postgres:16
    environment:
      POSTGRES_DB: telemetry
      POSTGRES_USER: telemetry
      POSTGRES_PASSWORD: telemetry
  commands:
    build: ./commands_service
    ports:
      - "8002:8002"
    environment:
      - DJANGO_SETTINGS_MODULE=commands_service.settings
    depends_on:
      - commands_db
      - redis
  commands_db:
    image: postgres:16
    environment:
      POSTGRES_DB: commands
      POSTGRES_USER: commands
      POSTGRES_PASSWORD: commands
  authentication:
    build: ./authentication_service
    ports:
      - "8003:8003"
    environment:
      - DJANGO_SETTINGS_MODULE=authentication_service.settings
    depends_on:
      - authentication_db
      - redis
  authentication_db:
    image: postgres:16
    environment:
      POSTGRES_DB: authentication
      POSTGRES_USER: authentication
      POSTGRES_PASSWORD: authentication
  dashboard:
    build: ./dashboard_service
    ports:
      - "8004:8004"
    environment:
      - DJANGO_SETTINGS_MODULE=dashboard_service.settings
    depends_on:
      - dashboard_db
      - redis
  dashboard_db:
    image: postgres:16
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: dashboard
      POSTGRES_PASSWORD: dashboard
  redis:
    image: redis:7